### ISSUE TITLE
放在cell里面初始设置value时无效

### ISSUE THREAD

**Issue by xiajinchun** [DuckDeck/StarReview#1]
当StarReview放在cell里，在`cellForItemAtIndexPath`方法里面设置startReview的value值时无效，显示的是空白值
除非再次调用`reloadData`或者设置 value 值才会更新view
不知道作者遇到类似问题没哇。

**Comment by DuckDeck** [comment]
我不知道你的代码是怎么样的,我这边有在Swift下测试,是没问题的,Objc里面我自己项目有用到,也没问题
比如我在cell里面
class  tbcell:UITableViewCell {
     var star:StarReview?
  star = StarReview()
        star?.starCount  = 12
        star?.frame = CGRect(x: 0, y: 200, width: 250, height: 40)
        addSubview(star!)
然后再
cell?.star?.value = Float(indexPath.row)
是可以设置value的

**Comment by xiajinchun** [comment]
我是在`awakeFromNib`方法里面去初始化StarReview的

**Comment by DuckDeck** [comment]
你在ViewDidLoad初始化试试

**Comment by xiajinchun** [comment]
cell 里面的 `awakeFromNib`，cell 哪来的`viewDidLoad`啊，但是在`viewDidLoad`里面去`tableview.reloadData()`，也无效。

**Comment by DuckDeck** [comment]
坑，搞错了。因为我不用storyboard或者xib.所以没试过awakwfromnib ,我都是用initwithframe或者initwithstyle.在这里面初始化的，然后在cellForItemAtIndexPath里面直接设置就行了。

**Comment by xiajinchun** [comment]
嗯。谢谢哈。我自己在看看～
